In [57]:
import math

import numpy as np

In [79]:
embedding_dim = 3

def softmax(x, t=1):
  return np.exp(x/t) / sum(np.exp(x/t))
  

def self_attention(input_values):
  gram = np.matmul(input_values.T, input_values)
  print(gram)
  scores = softmax(gram / np.sqrt(input_values.shape[1]))
  print(scores)
  return np.matmul(input_values, scores)
  

In [80]:
input = np.array([
  [1, 2, 1],
  [0, 4, 5],
  [2, 3, 8],
  [4, 5, 6],
])

self_attention(input)

[[ 21  28  41]
 [ 28  54  76]
 [ 41  76 126]]
[[9.65953629e-06 9.21460976e-13 4.86515787e-22]
 [5.49713662e-04 3.04591573e-06 2.90401061e-13]
 [9.99440627e-01 9.99996954e-01 1.00000000e+00]]


array([[1.00054971, 1.00000305, 1.        ],
       [4.99940199, 4.99999695, 5.        ],
       [7.99719347, 7.99998477, 8.        ],
       [5.99943097, 5.99999695, 6.        ]])